### ISSUE TITLE
Material/SurfaceShader Support

### ISSUE THREAD

**Issue by tankiJong** [tankiJong/urban#17]
#### Material
`Material` is a data-driven high-level concept to create different shading function to control the input for a specific step in the pixel shader for a certain shading model. #11 
After setting up all inputs, the user invokes `Material::Compile` to generate `Program`.
The Material compilation can be considered as a process of emitting HLSL code and insert them into the predefined shader templates, the engine will need to use shader reflection( which is a feature developed in #15 )  to properly parse the register index info.

#### Material instance
`MaterialInstance`(MI) is a `Material` with an overridden set of resource binding inputs. When drawing meshes with different MI, the only necessary operation should be calling `list.BindResource(mi.bindings())`. All MI share the same rest information, eg, binding layout, root signature...

#### TODOs:

- Material Creation
  - [ ] design the data file for the material format
    * described as a node-based structure for future(material editor)
  - [ ] Load material from a data file, or construct it by code #18 
    * the internal storage has to be friendly to emitting HLSL process
  - [ ] Compile material into the HLSL code snippet
    * three parts eventually: Binding declaration; Global functions; Shading function;
    * Shading function should be something like `void ShadingFunction(out float3 albedo, float3 
normal...)`, and be aware all shading functions probably will have the same signatures.
    * each texture shall have independent Sampler for convenience
    * optimization: scalars and vectors should be packed into a big ConstantBuffer
  - [ ] Inject the code snippet into pixel shader template, and compile it into a program.

- Material Instantiation
  - [ ] `MaterialInstance Material::Instantiate() const`
  - [ ] MI have a set of APIs: `SetTexture2(name, tex2)`, `SetSampler(texName, sampler)` `SetScalar(name, val)`, `SetVector(name, vec)`
